"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from decouple import Config, RepositoryEnv, UndefinedValueError

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ── Variables de entorno ──────────────────────────────────────────────────────
# Se cargan desde `chessapp-back/.env` (gitignored). Para crear/regenerar uno,
# copiar `.env.example` y rellenar. La key `DJANGO_SECRET_KEY` es obligatoria;
# si falta, la app se niega a arrancar (mejor un crash claro que una clave
# débil en producción).
_env_path = BASE_DIR / '.env'
if _env_path.exists():
    config = Config(RepositoryEnv(str(_env_path)))
else:
    # Sin .env (típico en CI o contenedor): leer de os.environ directamente.
    from decouple import config  # type: ignore  # fallback al singleton

try:
    SECRET_KEY = config('DJANGO_SECRET_KEY')
except UndefinedValueError as exc:
    raise RuntimeError(
        'DJANGO_SECRET_KEY no está definida. Crea `chessapp-back/.env` a partir '
        'de `.env.example` y rellena la clave (ver instrucciones dentro).'
    ) from exc

DEBUG = config('DJANGO_DEBUG', default='false', cast=lambda v: str(v).lower() == 'true')

# Lista separada por comas. Vacía → ningún host permitido (Django bloquea
# todo). Para añadir el tunnel: DJANGO_ALLOWED_HOSTS=localhost,tu-dominio.com
ALLOWED_HOSTS = [
    h.strip() for h in config('DJANGO_ALLOWED_HOSTS', default='').split(',') if h.strip()
]

# CORS: las apps móviles nativas no respetan CORS, así que esta política sólo
# afecta a clientes web. Mantenemos abierto en dev; en producción restringir.
CORS_ALLOW_ALL_ORIGINS = DEBUG

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Application definition

INSTALLED_APPS = [
    # daphne DEBE ir primero para sobreescribir el servidor de desarrollo de Django
    # y arrancar automáticamente el soporte ASGI/WebSocket con 'manage.py runserver'.
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    'src.games',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ── Django Channels ───────────────────────────────────────────────────────────
# Punto de entrada ASGI (combina HTTP + WebSocket).
# No definimos WSGI_APPLICATION: la app necesita WebSockets para el progreso
# del análisis, por lo que sólo se sirve vía Daphne/ASGI.
ASGI_APPLICATION = 'core.asgi.application'

# Canal en memoria para desarrollo (sin Redis).
# Para producción con múltiples workers, reemplazar por:
#   pip install channels-redis
#   CHANNEL_LAYERS = {
#       'default': {
#           'BACKEND': 'channels_redis.core.RedisChannelLayer',
#           'CONFIG': {'hosts': [('127.0.0.1', 6379)]},
#       }
#   }
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# En producción (Render, Neon, etc.) inyectamos DATABASE_URL como variable
# de entorno con la URL de PostgreSQL completa. En desarrollo local se usa
# SQLite por simplicidad.
_database_url = config('DATABASE_URL', default='')
if _database_url:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(_database_url, conn_max_age=600, ssl_require=True),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Extra places for collectstatic to find static files
STATICFILES_DIRS = []

# Whitenoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Cache (compartida entre hilo de análisis y WebSocket consumer) ────────────
# LocMemCache es thread-safe y no requiere servicios externos.
# Para producción con múltiples procesos, usar django-redis o memcached.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'chess-analysis-cache',
    }
}

# ── YOLOv8 — Detección de piezas ──────────────────────────────────────────────
# Ruta al modelo entrenado. El sistema usa detección por deltas si no existe.
CHESS_YOLO_MODEL_PATH = os.path.join(MEDIA_ROOT, 'models', 'chess_yolo.pt')
# Confianza mínima para aceptar una detección (0.0–1.0). Bajar si se pierden piezas.
CHESS_YOLO_CONFIDENCE = 0.4
# Sobrescribir nombres de clase del modelo si difieren del mapa por defecto:
# CHESS_YOLO_CLASS_MAP = {'my_class_name': 'P', ...}

# ── Subida de ficheros ────────────────────────────────────────────────────────
# Forzar streaming a disco desde el primer byte: evita que vídeos grandes se
# almacenen temporalmente en RAM antes de volcarse al disco.
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]
# Sin límite de RAM para uploads (todo va a disco directamente).
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB (irrelevante con TemporaryFileUploadHandler)

# ── DRF + JWT ─────────────────────────────────────────────────────────────────
# Autenticación JWT por defecto. Las vistas se siguen marcando explícitamente
# con `permission_classes` (IsAuthenticated en las protegidas, AllowAny en
# /register y /login). Así no rompemos vistas existentes hasta el siguiente
# paso, donde añadimos IsAuthenticated y filtros por usuario una a una.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    # 1 hora: balance entre seguridad y reauths molestas.
    'ACCESS_TOKEN_LIFETIME':  timedelta(hours=1),
    # 30 días: el cliente móvil refresca silenciosamente sin reabrir login.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    # Si True, cada refresh genera un refresh token nuevo (y revoca el viejo,
    # con app instalada `rest_framework_simplejwt.token_blacklist`). De momento
    # mantenemos el refresh estático para evitar la dependencia extra.
    'ROTATE_REFRESH_TOKENS': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

